# Generated by Django 4.2.5 on 2026-01-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piks', '0002_privatechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
